import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { CONFLICT_KEYS, INSERT_ONLY_COLUMNS, TABLE_ORDER, type Seed } from "./rows";

/**
 * Render the seed as one SQL script: insert ... on conflict do update per
 * table, in foreign-key order, inside a single transaction. Apply with psql
 * or paste into the Supabase SQL editor.
 */

/** Columns stored as jsonb. Every other array column is text[]. */
const JSONB_COLUMNS = new Set(["guardrails", "isbns", "store_links", "content"]);

function literal(value: unknown, column?: string): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  if (column && JSONB_COLUMNS.has(column)) return `${literal(JSON.stringify(value))}::jsonb`;
  if (Array.isArray(value)) {
    if (value.length === 0) return "'{}'::text[]";
    if (value.every((v) => typeof v === "string")) return `array[${value.map((v) => literal(v)).join(", ")}]::text[]`;
    throw new Error(`column ${column ?? "?"}: arrays must be text[] or a jsonb column`);
  }
  throw new Error(`column ${column ?? "?"}: objects need a jsonb column`);
}

function quoteIdent(name: string): string {
  if (!/^[a-z_][a-z0-9_]*$/.test(name)) throw new Error(`unsafe identifier ${name}`);
  return name;
}

function upsert(
  table: string,
  rows: Record<string, unknown>[],
  conflict: string[],
  skipColumns: string[] = [],
  insertOnly: readonly string[] = [],
): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const columns = Object.keys(rows[0]!).filter((c) => !skipColumns.includes(c));
  const updates = columns.filter((c) => !conflict.includes(c) && !insertOnly.includes(c));
  const lines = [
    `insert into public.${quoteIdent(table)} (${columns.map(quoteIdent).join(", ")})`,
    "values",
    rows.map((r) => `  (${columns.map((c) => literal(r[c], c)).join(", ")})`).join(",\n"),
    `on conflict (${conflict.map(quoteIdent).join(", ")}) do update set`,
    updates.map((c) => `  ${quoteIdent(c)} = excluded.${quoteIdent(c)}`).join(",\n") + ";",
  ];
  return lines.join("\n") + "\n";
}

export const SEED_SQL_HEADER = [
  "-- Akana catalogue seed. Generated by scripts/seed.ts --sql; do not edit by hand.",
  "-- Deterministic: the same inputs give the same file. Re-running upserts in place.",
  "-- workbooks.status is set on insert only, so a title released through public.release_version stays live when the seed runs again.",
  "-- Requires migrations 0001, 0002, 0015 (taxonomy flags) and 0025 (themes.status). The house organisation and marketplace tenant come from 0001.",
];

export interface RenderOptions {
  /** Comment lines above begin;. Defaults to SEED_SQL_HEADER. */
  header?: string[];
  /** Statements placed straight after begin;, before any insert. */
  preamble?: string[];
}

export function renderSeedSql(seed: Seed, opts: RenderOptions = {}): string {
  const parts: string[] = [...(opts.header ?? SEED_SQL_HEADER), "begin;", ...(opts.preamble ?? []), ""];
  for (const table of TABLE_ORDER) {
    const rows = seed[table] as unknown as Record<string, unknown>[];
    parts.push(`-- ${table} (${rows.length})`);
    // workbooks point at versions and versions point at workbooks, so the
    // pointer is written after the versions exist.
    const skip = table === "workbooks" ? ["current_version_id"] : [];
    parts.push(upsert(table, rows, CONFLICT_KEYS[table], skip, INSERT_ONLY_COLUMNS[table] ?? []));
  }
  const pointed = seed.workbooks.filter((w) => w.current_version_id);
  parts.push(`-- workbooks.current_version_id (${pointed.length})`);
  for (const w of pointed) {
    parts.push(`update public.workbooks set current_version_id = ${literal(w.current_version_id)} where id = ${literal(w.id)};`);
  }
  parts.push("", "commit;", "");
  return parts.join("\n");
}

export function writeSeedSql(seed: Seed, path: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, renderSeedSql(seed), "utf8");
}
