import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { buildSeedV2, repoRoot, type BuildOptions } from "./build";
import type { Seed } from "./rows";
import { renderSeedSql } from "./sql";

/**
 * Demo Catalogue v2 preview (F-153).
 *
 * v2 waits for Crent's approval of the titles. Until then it is built only as
 * a preview: supabase/seed/seed_v2_preview.sql. supabase/seed/seed.sql is
 * still built from v1 and does not change. There is no apply path for v2.
 *
 * The preview refuses to run unless the session sets
 * akana.apply_v2_preview = 'yes', so pasting it into the SQL editor of a real
 * project fails inside the transaction and writes nothing.
 */

export const V2_PREVIEW_PATH = ["supabase", "seed", "seed_v2_preview.sql"];

export const V2_PREVIEW_HEADER = [
  "-- DO NOT APPLY UNTIL CRENT APPROVES.",
  "-- Akana catalogue seed, Demo Catalogue v2 PREVIEW (F-153). Built from docs/planning/AK_Demo_Catalogue_v2.json.",
  "-- Generated by pnpm --filter @akana/seed preview:v2; do not edit by hand. Deterministic: the same inputs give the same file.",
  "-- Not for staging or production. The titles, codes and Theme placements wait for Crent's approval;",
  "-- see docs/planning/AK_Demo_Catalogue_v2_Notes.md for the steps after approval.",
  "-- The guard below stops this script unless the session sets akana.apply_v2_preview = 'yes' (scratch databases only).",
  "-- Requires migrations 0001, 0002, 0015 (taxonomy flags) and 0025 (themes.status).",
];

export const V2_PREVIEW_GUARD = [
  "do $guard$",
  "begin",
  "  if coalesce(current_setting('akana.apply_v2_preview', true), '') <> 'yes' then",
  "    raise exception 'seed_v2_preview.sql is a preview. DO NOT APPLY UNTIL CRENT APPROVES (F-153).';",
  "  end if;",
  "end",
  "$guard$;",
];

export function renderSeedV2PreviewSql(seed: Seed): string {
  return renderSeedSql(seed, { header: V2_PREVIEW_HEADER, preamble: V2_PREVIEW_GUARD });
}

export function writeSeedV2Preview(opts: Omit<BuildOptions, "catalogue"> = {}): { path: string; seed: Seed } {
  const root = opts.root ?? repoRoot();
  const seed = buildSeedV2({ root });
  const path = join(root, ...V2_PREVIEW_PATH);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, renderSeedV2PreviewSql(seed), "utf8");
  return { path, seed };
}
